### ISSUE TITLE
Jitsi connection fails from Android devices

### ISSUE THREAD

**Issue by micoots** [humhub-contrib/jitsi-meet#10]
### What steps will reproduce the problem?

Try and start Jitsi Meet from Humhub

### What is the expected result?

Jitsi Meet connects to meet.jit.si and opens a room.

### What do you get instead?

Endless circling as discussed here:

[https://community.humhub.com/s/general-discussion/?contentId=215626](https://community.humhub.com/s/general-discussion/?contentId=215626)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1 (also tested with 1.4.4)
| PHP version      |  7.4 (also tested with 7.3)
| Operating system | CentOS Linux release 8.1.1911 (Core)

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.

No errors exist, just connection to meet.jit.si from Android devices I've tested never works. 

Have tested on different Android devices - 3 different model phones and 1 Samsung tablet. Works fine from a PC and web browser.

Have also tested from HumHub.com cloud by creating a domain there and testing, also fails from Android devices.

From the same devices, I can start and use the Jitsi Android App by itself from the Android devices, opens and can start a room no problems.

Side note: I have also installed my own Jitsi server under my own domain name, it took an effort to get going but it does work and I've tested exactly the above on it, via the Jitsi module, has exactly the same problems as experienced about with meet.jit.si and accessed from the humhub.com cloud and my own hosting.

I really want this working so your help is appreciated.

**Comment by micoots** [comment]
Hi. Just following this up, essentially, this is the only thing holding me back from getting HumHub online for our group.

Any ideas? I've done all the trouble-shooting I can think of, apart from looking at the code, what else ?

Thanks.

**Comment by luke-** [comment]
Can you please test the workaround?

**Comment by micoots** [comment]
You are a genius Luke, thank you so much it works perfectly!
