### ISSUE TITLE
Link to this repository not working in the marketplace

### ISSUE THREAD

**Issue by funkycram** [humhub-contrib/jitsi-meet#26]
Go to https://www.humhub.com/en/marketplace/jitsi-meet/
Click on "Website:" link
You have a 404 page because the link is https://github.com/humhub-contrib/jtisi-meet instead of https://github.com/humhub-contrib/jitsi-meet (a `i` is missing in `jitsi`).
Should be fixed on https://partner.humhub.com/

**Comment by luke-** [comment]
Fixed
