### ISSUE TITLE
Jitsi meet module for easy integration of videoconferencingin Humhub

### ISSUE THREAD

**Issue by blu-IT** [humhub-contrib/jitsi-meet#5]
Hello,

I know that it's not a big deal to send around a link for **"Jitsi meet"** link for videoconferencing,
but I like the way it has been integrated/solved in slack for example.

I think it would also be a nice feature to offer space-specific and individual jitsi-meet integration for Humhub. Especially in these times...

**What does the Jitsi plugin for Slack do?**

"_This integration adds the /jitsi slash command for your team so that you can start a video conference in your channel, making it easy for everyone to just jump on the call. Just type /jitsi into your channel and a conference link will be provided in the channel. Additionally, you can send direct messages to users by mentioning their username in the command. In addition to simple video calls Jitsi Meet also lets you join over the phone, stream to YouTube and collaboratively edit documents._"

**Looks like this:**

![Screenshot_2020-04-01 Slack jitsi_meet_vc blu IT](https://user-images.githubusercontent.com/13665806/78123119-fdd1bf80-740d-11ea-9012-caced45c3033.png)

and **creates a individual link** to the conference:

`https://meet.jit.si/some-slack-space/FuriousPearsCodeNowhere`

Thanks!

Best wishes and regards

**Comment by blu-IT** [comment]
Hey,

thanks for the quick development - **great!!!**

I have a litte suggestion for a improvement:
 
When clicking on the Jitsi-Meet icon in the tool bar, the next page asks for "Name" which _is intended to insert a conference room name_ **BUT** many people who are not familiar with that, could think that **they have to insert their own name.**

The automatic integration of the own (humhub-) name into jitsi-meet is awsome! 
If possible it would also be nice, when jitsi-meet recognizes from the humhub settings the language and also switches to that ;-)

**Comment by luke-** [comment]
@blu-IT Can you please open separate issues for each RFE? Thanks!
