### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by vtomasi** [humhub-contrib/jitsi-meet#6]
hi, I installed jitsi meet on our humhub platform 1.4.4 often frequented by non-digital natives. in certain situations with desktop connections it shows an empty page and cookies must be enabled in order to confirm the devices required by jitsi, microphone and camera. I was wondering if there is a possibility to exclude this problem to facilitate inexperienced people

**Comment by luke-** [comment]
Strange, can you provide steps to reproduce?
