### ISSUE TITLE
CSP blocks request 

### ISSUE THREAD

**Issue by aronbos** [humhub-contrib/jitsi-meet#8]
In Jiti meet version 1.1 I the frame-scr has to be specified as well:
```
`                    "frame-src" => [
                        "self" => true,
                        "allow" => [  
                            "https://www.youtube.com",
                            "https://meet.jit.si",
                        ]                        
                    ],
                    "script-src" => [
                        "self" => true,
                        "allow" => [
                          'https://meet.jit.si/external_api.js'
                        `],
```
After making this adjustment, it works wonderful.

**Comment by jorge-vitrubio** [comment]
hello, 
I was just trying to set this but every time I do write those settings the humhub instance fezzes.
```
return [
  "modules" => [
    "web" => [
      "security" => [
        "csp" => [
          "frame-src" => [
            "self" => true,
            "allow" => [
              "https://www.youtube.com",
              "https://meet.jit.si"
            ]
          ]
          "script-src" => [
            "self" => true,
            "allow" => [
              "https://meet.jit.si/external_api.js"
            ]
          ]
        ]
      ]
    ]
  ]     
];
```

**Comment by aronbos** [comment]
You need the complete CSP like:
`       ...,
        'web' => [
            'security' =>  [
                "headers" => [
                     "Strict-Transport-Security" => "max-age=31536000",
                    "X-XSS-Protection" => "1; mode=block", 
                    "X-Content-Type-Options" => "nosniff",
                    "X-Frame-Options" => "deny",
                    "Referrer-Policy" => "no-referrer-when-downgrade",
                    "X-Permitted-Cross-Domain-Policies" => "master-only",
                ],
                "csp" => [
                    "nonce" => true,
                    "report-only" => false,
                    "report" => false,
                    "default-src" => [
                        "self" => true
                    ],
                    "img-src" => [
                        "data" => true,
                        "allow" => [
                            "*"
                        ]
                    ],
                    "font-src" => [
                        "self" => true
                    ],
                    "style-src" => [
                        "self" => true,
                        "unsafe-inline" => true
                    ],
                    "object-src" => [],
                    "frame-src" => [
                        "self" => true,
                        "allow" => [  
                            "https://www.youtube.com",
                            "https://meet.jit.si",
                        ]                        
                    ],
                    "script-src" => [
                        "self" => true,
                        "allow" => [
                          'https://meet.jit.si/external_api.js'
                        ],
                        "unsafe-inline" => true,
                        "unsafe-eval" => false,
                        "report-sample" => true
                    ],
                    "upgrade-insecure-requests" => true
                ]
            ]
        ],     
...   
`

**Comment by buddh4** [comment]
Would be great if modules could inject or at least check and warn about csp related issues.

**Comment by buddh4** [comment]
I've added the `frame-src` requirement to README.md. Thanks for reporting.
